In [1]:
from simtk.openmm.app import PDBFile
from simtk.openmm.app import * #the star brings in the entire package
from simtk.openmm import *
from simtk.unit import *

import pandas as pd
import numpy as np
import sys



In [2]:
#pdb = PDBFile("SS_B.pdb") #uploading the PDB file and defien it as an object (?)
pdb = PDBFile("/network/rit/home/ID653677/ChenRNALab/idengos/CD44/SS_B/SS_B_nores/SS_B.pdb")

In [3]:
top = pdb.getTopology()
pos = pdb.getPositions()

In [4]:
top.__dict__ #you're not supposed to mess with things with underscores, 
#definietly not supposed to mess with things with double underscores because you'll really regret it

{'_chains': [<Chain 0>],
 '_numResidues': 48,
 '_numAtoms': 1525,
 '_bonds': [Bond(<Atom 8 (C1') of chain 0 residue 0 (U)>, <Atom 21 (C2') of chain 0 residue 0 (U)>),
  Bond(<Atom 8 (C1') of chain 0 residue 0 (U)>, <Atom 9 (H1') of chain 0 residue 0 (U)>),
  Bond(<Atom 8 (C1') of chain 0 residue 0 (U)>, <Atom 10 (N1) of chain 0 residue 0 (U)>),
  Bond(<Atom 8 (C1') of chain 0 residue 0 (U)>, <Atom 7 (O4') of chain 0 residue 0 (U)>),
  Bond(<Atom 13 (C2) of chain 0 residue 0 (U)>, <Atom 10 (N1) of chain 0 residue 0 (U)>),
  Bond(<Atom 13 (C2) of chain 0 residue 0 (U)>, <Atom 15 (N3) of chain 0 residue 0 (U)>),
  Bond(<Atom 13 (C2) of chain 0 residue 0 (U)>, <Atom 14 (O2) of chain 0 residue 0 (U)>),
  Bond(<Atom 21 (C2') of chain 0 residue 0 (U)>, <Atom 25 (C3') of chain 0 residue 0 (U)>),
  Bond(<Atom 21 (C2') of chain 0 residue 0 (U)>, <Atom 22 (H2') of chain 0 residue 0 (U)>),
  Bond(<Atom 21 (C2') of chain 0 residue 0 (U)>, <Atom 23 (O2') of chain 0 residue 0 (U)>),
  Bond(<Atom 25 (

In [5]:
list(top.atoms())

[<Atom 0 (HO5') of chain 0 residue 0 (U)>,
 <Atom 1 (O5') of chain 0 residue 0 (U)>,
 <Atom 2 (C5') of chain 0 residue 0 (U)>,
 <Atom 3 (H5') of chain 0 residue 0 (U)>,
 <Atom 4 (H5'') of chain 0 residue 0 (U)>,
 <Atom 5 (C4') of chain 0 residue 0 (U)>,
 <Atom 6 (H4') of chain 0 residue 0 (U)>,
 <Atom 7 (O4') of chain 0 residue 0 (U)>,
 <Atom 8 (C1') of chain 0 residue 0 (U)>,
 <Atom 9 (H1') of chain 0 residue 0 (U)>,
 <Atom 10 (N1) of chain 0 residue 0 (U)>,
 <Atom 11 (C6) of chain 0 residue 0 (U)>,
 <Atom 12 (H6) of chain 0 residue 0 (U)>,
 <Atom 13 (C2) of chain 0 residue 0 (U)>,
 <Atom 14 (O2) of chain 0 residue 0 (U)>,
 <Atom 15 (N3) of chain 0 residue 0 (U)>,
 <Atom 16 (H3) of chain 0 residue 0 (U)>,
 <Atom 17 (C4) of chain 0 residue 0 (U)>,
 <Atom 18 (O4) of chain 0 residue 0 (U)>,
 <Atom 19 (C5) of chain 0 residue 0 (U)>,
 <Atom 20 (H5) of chain 0 residue 0 (U)>,
 <Atom 21 (C2') of chain 0 residue 0 (U)>,
 <Atom 22 (H2') of chain 0 residue 0 (U)>,
 <Atom 23 (O2') of chain 0 res

In [6]:
list(top.residues())

[<Residue 0 (U) of chain 0>,
 <Residue 1 (A) of chain 0>,
 <Residue 2 (G) of chain 0>,
 <Residue 3 (G) of chain 0>,
 <Residue 4 (C) of chain 0>,
 <Residue 5 (C) of chain 0>,
 <Residue 6 (A) of chain 0>,
 <Residue 7 (C) of chain 0>,
 <Residue 8 (U) of chain 0>,
 <Residue 9 (A) of chain 0>,
 <Residue 10 (U) of chain 0>,
 <Residue 11 (G) of chain 0>,
 <Residue 12 (U) of chain 0>,
 <Residue 13 (G) of chain 0>,
 <Residue 14 (U) of chain 0>,
 <Residue 15 (U) of chain 0>,
 <Residue 16 (G) of chain 0>,
 <Residue 17 (U) of chain 0>,
 <Residue 18 (U) of chain 0>,
 <Residue 19 (A) of chain 0>,
 <Residue 20 (C) of chain 0>,
 <Residue 21 (U) of chain 0>,
 <Residue 22 (G) of chain 0>,
 <Residue 23 (C) of chain 0>,
 <Residue 24 (C) of chain 0>,
 <Residue 25 (A) of chain 0>,
 <Residue 26 (U) of chain 0>,
 <Residue 27 (G) of chain 0>,
 <Residue 28 (G) of chain 0>,
 <Residue 29 (C) of chain 0>,
 <Residue 30 (A) of chain 0>,
 <Residue 31 (G) of chain 0>,
 <Residue 32 (U) of chain 0>,
 <Residue 33 (G) of 

In [7]:
res = list(top.residues())[0]

In [8]:
for atom in res.atoms():
    print(atom.id)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28


In [9]:
res.id


'1'

In [10]:
res.name

'U'

In [11]:
for atom in res.atoms():
    print(atom.name, atom.id)

HO5' 1
O5' 2
C5' 3
H5' 4
H5'' 5
C4' 6
H4' 7
O4' 8
C1' 9
H1' 10
N1 11
C6 12
H6 13
C2 14
O2 15
N3 16
H3 17
C4 18
O4 19
C5 20
H5 21
C2' 22
H2' 23
O2' 24
HO2' 25
C3' 26
H3' 27
O3' 28


In [12]:
for chain in top.chains():
    print("CHAIN %s" % chain.id)
    for res in chain.residues():
        print("RES %s" % res.name)
        for atom in res.atoms():
            if "C3" in atom.name:
                print(atom.residue.id, atom.index)

CHAIN A
RES U
1 25
RES A
2 58
RES G
3 92
RES G
4 126
RES C
5 157
RES C
6 188
RES A
7 221
RES C
8 252
RES U
9 282
RES A
10 315
RES U
11 345
RES G
12 379
RES U
13 409
RES G
14 443
RES U
15 473
RES U
16 503
RES G
17 537
RES U
18 567
RES U
19 597
RES A
20 630
RES C
21 661
RES U
22 691
RES G
23 725
RES C
24 756
RES C
25 787
RES A
26 820
RES U
27 850
RES G
28 884
RES G
29 918
RES C
30 949
RES A
31 982
RES G
32 1016
RES U
33 1046
RES G
34 1080
RES U
35 1110
RES C
36 1141
RES U
37 1171
RES U
38 1201
RES A
39 1234
RES G
40 1268
RES C
41 1299
RES U
42 1329
RES G
43 1363
RES G
44 1397
RES U
45 1427
RES U
46 1457
RES G
47 1491
RES U
48 1522


In [13]:
pdb.positions

Quantity(value=[Vec3(x=-0.05430000000000001, y=-0.1321, z=-0.0952), Vec3(x=-0.0684, y=-0.0409, z=-0.06820000000000001), Vec3(x=0.0595, y=0.0125, z=-0.0313), Vec3(x=0.0631, y=0.1188, z=-0.05580000000000001), Vec3(x=0.1379, y=-0.038900000000000004, z=-0.08650000000000001), Vec3(x=0.0847, y=-0.0051, z=0.11670000000000001), Vec3(x=0.1927, y=-0.0034000000000000002, z=0.1321), Vec3(x=0.013900000000000003, y=0.09970000000000001, z=0.1886), Vec3(x=-0.056299999999999996, y=0.044000000000000004, z=0.2981), Vec3(x=-0.037, y=0.10800000000000001, z=0.38420000000000004), Vec3(x=-0.20030000000000003, y=0.049600000000000005, z=0.2687), Vec3(x=-0.24660000000000004, y=0.0717, z=0.1408), Vec3(x=-0.1743, y=0.08460000000000001, z=0.0603), Vec3(x=-0.2882, y=0.0322, z=0.37410000000000004), Vec3(x=-0.2515, y=0.0121, z=0.4883), Vec3(x=-0.42100000000000004, y=0.039400000000000004, z=0.3407), Vec3(x=-0.48680000000000007, y=0.027200000000000002, z=0.4162), Vec3(x=-0.47400000000000003, y=0.0614, z=0.2155), Vec3(x=

In [14]:
atom = list(top.atoms())[45]
print(pdb.positions[atom.index]*angstroms)

Vec3(x=-0.07083, y=-0.04109, z=-0.0055000000000000005) nm**2


In [15]:
atom.element.name

'nitrogen'

In [16]:
import numpy as np
new_pos = pdb.getPositions(True)
new_pos += np.array([0.0, 0.5, 0.3])*angstroms
PDBFile.writeFile(top, new_pos)

REMARK   1 CREATED WITH OPENMM 7.4.2, 2021-11-08
ATOM      1 HO5'   U A   1      -0.543  -0.821  -0.652  1.00  0.00           H  
ATOM      2  O5'   U A   1      -0.684   0.091  -0.382  1.00  0.00           O  
ATOM      3  C5'   U A   1       0.595   0.625  -0.013  1.00  0.00           C  
ATOM      4  H5'   U A   1       0.631   1.688  -0.258  1.00  0.00           H  
ATOM      5 H5''   U A   1       1.379   0.111  -0.565  1.00  0.00           H  
ATOM      6  C4'   U A   1       0.847   0.449   1.467  1.00  0.00           C  
ATOM      7  H4'   U A   1       1.927   0.466   1.621  1.00  0.00           H  
ATOM      8  O4'   U A   1       0.139   1.497   2.186  1.00  0.00           O  
ATOM      9  C1'   U A   1      -0.563   0.940   3.281  1.00  0.00           C  
ATOM     10  H1'   U A   1      -0.370   1.580   4.142  1.00  0.00           H  
ATOM     11  N1    U A   1      -2.003   0.996   2.987  1.00  0.00           N  
ATOM     12  C6    U A   1      -2.466   1.217   1.708  1.00

In [17]:
PDBFile.writeFile(top, new_pos, open('new_pdb.pdb', 'w'))

In [18]:
pdb.getPositions(True)/nanometer #unitless

array([[-0.0543, -0.1321, -0.0952],
       [-0.0684, -0.0409, -0.0682],
       [ 0.0595,  0.0125, -0.0313],
       ...,
       [-1.4272,  0.3164, -0.1817],
       [-1.4878,  0.3653, -0.0614],
       [-1.5393,  0.2934, -0.024 ]])

In [19]:
pwd

'/network/rit/home/ID653677/ChenRNALab/idengos'

In [20]:
a = np.random.random(15).reshape((5, 3))
b = np.array([1, 2, 3])
print(a)
print(a - b)
np.linalg.norm(a - b, axis=1)

[[0.57494585 0.43435532 0.00924064]
 [0.92809259 0.79095526 0.75069765]
 [0.95594968 0.05327466 0.33759503]
 [0.28151176 0.18560489 0.43442749]
 [0.420733   0.4305968  0.58743854]]
[[-0.42505415 -1.56564468 -2.99075936]
 [-0.07190741 -1.20904474 -2.24930235]
 [-0.04405032 -1.94672534 -2.66240497]
 [-0.71848824 -1.81439511 -2.56557251]
 [-0.579267   -1.5694032  -2.41256146]]


array([3.40243381, 2.5546665 , 3.29849666, 3.22341702, 2.93581836])

In [29]:
for L in range(47, 12):
    print(L)

In [24]:
print(y)

range(47, 12, -1)


In [14]:

k=14
list(range(47,12,-1))

[47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13]

In [15]:
import numpy as np
a = np.empty(5)
5 * a
print(a)


b = [k] * 5
print(b)

[0. 0. 0. 0. 0.]
[14, 14, 14, 14, 14]
